[package]
name = "lakeshire-cli"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
lakeshire-core = { workspace = true }
anyhow = { workspace = true }
png = "0.17.8"
enigo = { workspace = true }
