# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Lakeshire.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'Lakeshire.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fLakeshire.proto\x12\tlakeshire\"\x80\x01\n\tGameState\x12%\n\x08\x42otState\x18\x01 \x02(\x0e\x32\x13.lakeshire.BotState\x12%\n\x06Player\x18\x02 \x02(\x0b\x32\x15.lakeshire.PlayerInfo\x12%\n\x06Target\x18\x03 \x01(\x0b\x32\x15.lakeshire.TargetInfo\"d\n\nPlayerInfo\x12!\n\x08UnitInfo\x18\x01 \x02(\x0b\x32\x0f.lakeshire.Unit\x12$\n\x07PosInfo\x18\x02 \x02(\x0b\x32\x13.lakeshire.Position\x12\r\n\x05\x46lags\x18\x03 \x02(\x04\"/\n\nTargetInfo\x12!\n\x08UnitInfo\x18\x01 \x02(\x0b\x32\x0f.lakeshire.Unit\"\x96\x01\n\x04Unit\x12\x0c\n\x04Name\x18\x01 \x02(\t\x12\r\n\x05Level\x18\x02 \x02(\x03\x12\x1f\n\x05\x43lass\x18\x03 \x01(\x0e\x32\x10.lakeshire.Class\x12\x15\n\rHealthCurrent\x18\x04 \x02(\x03\x12\x11\n\tHealthMax\x18\x05 \x02(\x03\x12\x14\n\x0cPowerCurrent\x18\x06 \x01(\x03\x12\x10\n\x08PowerMax\x18\x07 \x01(\x03\"y\n\x08Position\x12\x0c\n\x04MapX\x18\x01 \x02(\x04\x12\x0c\n\x04MapY\x18\x02 \x02(\x04\x12\r\n\x05MapId\x18\x03 \x02(\x04\x12\x0e\n\x06WorldX\x18\x04 \x02(\x03\x12\x0e\n\x06WorldY\x18\x05 \x02(\x03\x12\x12\n\nInstanceId\x18\x06 \x02(\x04\x12\x0e\n\x06\x46\x61\x63ing\x18\x07 \x02(\x04*1\n\x08\x42otState\x12\x0b\n\x07Stopped\x10\x00\x12\x0b\n\x07Running\x10\x01\x12\x0b\n\x07\x44umpPos\x10\x02*\x97\x01\n\x05\x43lass\x12\x08\n\x04None\x10\x00\x12\x0b\n\x07Warrior\x10\x01\x12\x0b\n\x07Paladin\x10\x02\x12\n\n\x06Hunter\x10\x03\x12\t\n\x05Rogue\x10\x04\x12\n\n\x06Priest\x10\x05\x12\x0f\n\x0b\x44\x65\x61thKnight\x10\x06\x12\n\n\x06Shaman\x10\x07\x12\x08\n\x04Mage\x10\x08\x12\x0b\n\x07Warlock\x10\t\x12\x08\n\x04Monk\x10\n\x12\t\n\x05\x44ruid\x10\x0b')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Lakeshire_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOTSTATE']._serialized_start=588
  _globals['_BOTSTATE']._serialized_end=637
  _globals['_CLASS']._serialized_start=640
  _globals['_CLASS']._serialized_end=791
  _globals['_GAMESTATE']._serialized_start=31
  _globals['_GAMESTATE']._serialized_end=159
  _globals['_PLAYERINFO']._serialized_start=161
  _globals['_PLAYERINFO']._serialized_end=261
  _globals['_TARGETINFO']._serialized_start=263
  _globals['_TARGETINFO']._serialized_end=310
  _globals['_UNIT']._serialized_start=313
  _globals['_UNIT']._serialized_end=463
  _globals['_POSITION']._serialized_start=465
  _globals['_POSITION']._serialized_end=586
# @@protoc_insertion_point(module_scope)
