"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _BotState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BotStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BotState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Stopped: _BotState.ValueType  # 0
    Running: _BotState.ValueType  # 1
    DumpPos: _BotState.ValueType  # 2

class BotState(_BotState, metaclass=_BotStateEnumTypeWrapper): ...

Stopped: BotState.ValueType  # 0
Running: BotState.ValueType  # 1
DumpPos: BotState.ValueType  # 2
global___BotState = BotState

class _Class:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ClassEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Class.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Warrior: _Class.ValueType  # 1
    Paladin: _Class.ValueType  # 2
    Hunter: _Class.ValueType  # 3
    Rogue: _Class.ValueType  # 4
    Priest: _Class.ValueType  # 5
    DeathKnight: _Class.ValueType  # 6
    Shaman: _Class.ValueType  # 7
    Mage: _Class.ValueType  # 8
    Warlock: _Class.ValueType  # 9
    Monk: _Class.ValueType  # 10
    Druid: _Class.ValueType  # 11

class Class(_Class, metaclass=_ClassEnumTypeWrapper): ...

Warrior: Class.ValueType  # 1
Paladin: Class.ValueType  # 2
Hunter: Class.ValueType  # 3
Rogue: Class.ValueType  # 4
Priest: Class.ValueType  # 5
DeathKnight: Class.ValueType  # 6
Shaman: Class.ValueType  # 7
Mage: Class.ValueType  # 8
Warlock: Class.ValueType  # 9
Monk: Class.ValueType  # 10
Druid: Class.ValueType  # 11
global___Class = Class

@typing.final
class GameState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOTSTATE_FIELD_NUMBER: builtins.int
    PLAYER_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    BotState: global___BotState.ValueType
    @property
    def Player(self) -> global___PlayerInfo: ...
    @property
    def Target(self) -> global___TargetInfo: ...
    def __init__(
        self,
        *,
        BotState: global___BotState.ValueType | None = ...,
        Player: global___PlayerInfo | None = ...,
        Target: global___TargetInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["BotState", b"BotState", "Player", b"Player", "Target", b"Target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["BotState", b"BotState", "Player", b"Player", "Target", b"Target"]) -> None: ...

global___GameState = GameState

@typing.final
class PlayerInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNITINFO_FIELD_NUMBER: builtins.int
    POSINFO_FIELD_NUMBER: builtins.int
    FLAGS_FIELD_NUMBER: builtins.int
    Flags: builtins.int
    """Since booleans don't work in lua-pb, we pack them into a single u64 instead
    The flags in order from least significant bit to most significant bit are:
    IsOutdoors, IsMounted, IsFlying
    """
    @property
    def UnitInfo(self) -> global___Unit: ...
    @property
    def PosInfo(self) -> global___Position: ...
    def __init__(
        self,
        *,
        UnitInfo: global___Unit | None = ...,
        PosInfo: global___Position | None = ...,
        Flags: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Flags", b"Flags", "PosInfo", b"PosInfo", "UnitInfo", b"UnitInfo"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Flags", b"Flags", "PosInfo", b"PosInfo", "UnitInfo", b"UnitInfo"]) -> None: ...

global___PlayerInfo = PlayerInfo

@typing.final
class TargetInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNITINFO_FIELD_NUMBER: builtins.int
    @property
    def UnitInfo(self) -> global___Unit: ...
    def __init__(
        self,
        *,
        UnitInfo: global___Unit | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["UnitInfo", b"UnitInfo"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["UnitInfo", b"UnitInfo"]) -> None: ...

global___TargetInfo = TargetInfo

@typing.final
class Unit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    CLASS_FIELD_NUMBER: builtins.int
    HEALTHCURRENT_FIELD_NUMBER: builtins.int
    HEALTHMAX_FIELD_NUMBER: builtins.int
    POWERCURRENT_FIELD_NUMBER: builtins.int
    POWERMAX_FIELD_NUMBER: builtins.int
    Name: builtins.str
    Level: builtins.int
    Class: global___Class.ValueType
    HealthCurrent: builtins.int
    HealthMax: builtins.int
    PowerCurrent: builtins.int
    PowerMax: builtins.int
    def __init__(
        self,
        *,
        Name: builtins.str | None = ...,
        Level: builtins.int | None = ...,
        Class: global___Class.ValueType | None = ...,
        HealthCurrent: builtins.int | None = ...,
        HealthMax: builtins.int | None = ...,
        PowerCurrent: builtins.int | None = ...,
        PowerMax: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Class", b"Class", "HealthCurrent", b"HealthCurrent", "HealthMax", b"HealthMax", "Level", b"Level", "Name", b"Name", "PowerCurrent", b"PowerCurrent", "PowerMax", b"PowerMax"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Class", b"Class", "HealthCurrent", b"HealthCurrent", "HealthMax", b"HealthMax", "Level", b"Level", "Name", b"Name", "PowerCurrent", b"PowerCurrent", "PowerMax", b"PowerMax"]) -> None: ...

global___Unit = Unit

@typing.final
class Position(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAPX_FIELD_NUMBER: builtins.int
    MAPY_FIELD_NUMBER: builtins.int
    MAPID_FIELD_NUMBER: builtins.int
    WORLDX_FIELD_NUMBER: builtins.int
    WORLDY_FIELD_NUMBER: builtins.int
    INSTANCEID_FIELD_NUMBER: builtins.int
    FACING_FIELD_NUMBER: builtins.int
    MapX: builtins.int
    MapY: builtins.int
    MapId: builtins.int
    WorldX: builtins.int
    WorldY: builtins.int
    InstanceId: builtins.int
    Facing: builtins.int
    def __init__(
        self,
        *,
        MapX: builtins.int | None = ...,
        MapY: builtins.int | None = ...,
        MapId: builtins.int | None = ...,
        WorldX: builtins.int | None = ...,
        WorldY: builtins.int | None = ...,
        InstanceId: builtins.int | None = ...,
        Facing: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Facing", b"Facing", "InstanceId", b"InstanceId", "MapId", b"MapId", "MapX", b"MapX", "MapY", b"MapY", "WorldX", b"WorldX", "WorldY", b"WorldY"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Facing", b"Facing", "InstanceId", b"InstanceId", "MapId", b"MapId", "MapX", b"MapX", "MapY", b"MapY", "WorldX", b"WorldX", "WorldY", b"WorldY"]) -> None: ...

global___Position = Position
