// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file Lakeshire.proto (syntax proto2)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file Lakeshire.proto.
 */
export const file_Lakeshire: GenFile = /*@__PURE__*/
  fileDesc("Cg9MYWtlc2hpcmUucHJvdG8iYgoJR2FtZVN0YXRlEhsKCEJvdFN0YXRlGAEgAigOMgkuQm90U3RhdGUSGwoGUGxheWVyGAIgAigLMgsuUGxheWVySW5mbxIbCgZUYXJnZXQYAyABKAsyCy5UYXJnZXRJbmZvIlAKClBsYXllckluZm8SFwoIVW5pdEluZm8YASACKAsyBS5Vbml0EhoKB1Bvc0luZm8YAiACKAsyCS5Qb3NpdGlvbhINCgVGbGFncxgDIAIoBCIlCgpUYXJnZXRJbmZvEhcKCFVuaXRJbmZvGAEgAigLMgUuVW5pdCKMAQoEVW5pdBIMCgROYW1lGAEgAigJEg0KBUxldmVsGAIgAigDEhUKBUNsYXNzGAMgASgOMgYuQ2xhc3MSFQoNSGVhbHRoQ3VycmVudBgEIAIoAxIRCglIZWFsdGhNYXgYBSACKAMSFAoMUG93ZXJDdXJyZW50GAYgASgDEhAKCFBvd2VyTWF4GAcgASgDInkKCFBvc2l0aW9uEgwKBE1hcFgYASACKAQSDAoETWFwWRgCIAIoBBINCgVNYXBJZBgDIAIoBBIOCgZXb3JsZFgYBCACKAMSDgoGV29ybGRZGAUgAigDEhIKCkluc3RhbmNlSWQYBiACKAQSDgoGRmFjaW5nGAcgAigEKjEKCEJvdFN0YXRlEgsKB1N0b3BwZWQQABILCgdSdW5uaW5nEAESCwoHRHVtcFBvcxACKpcBCgVDbGFzcxIICgROb25lEAASCwoHV2FycmlvchABEgsKB1BhbGFkaW4QAhIKCgZIdW50ZXIQAxIJCgVSb2d1ZRAEEgoKBlByaWVzdBAFEg8KC0RlYXRoS25pZ2h0EAYSCgoGU2hhbWFuEAcSCAoETWFnZRAIEgsKB1dhcmxvY2sQCRIICgRNb25rEAoSCQoFRHJ1aWQQCw");

/**
 * @generated from message GameState
 */
export type GameState = Message<"GameState"> & {
  /**
   * @generated from field: required BotState BotState = 1;
   */
  BotState: BotState;

  /**
   * @generated from field: required PlayerInfo Player = 2;
   */
  Player?: PlayerInfo;

  /**
   * @generated from field: optional TargetInfo Target = 3;
   */
  Target?: TargetInfo;
};

/**
 * Describes the message GameState.
 * Use `create(GameStateSchema)` to create a new message.
 */
export const GameStateSchema: GenMessage<GameState> = /*@__PURE__*/
  messageDesc(file_Lakeshire, 0);

/**
 * @generated from message PlayerInfo
 */
export type PlayerInfo = Message<"PlayerInfo"> & {
  /**
   * @generated from field: required Unit UnitInfo = 1;
   */
  UnitInfo?: Unit;

  /**
   * @generated from field: required Position PosInfo = 2;
   */
  PosInfo?: Position;

  /**
   * Since booleans don't work in lua-pb, we pack them into a single u64 instead
   * The flags in order from least significant bit to most significant bit are:
   * IsOutdoors, IsMounted, IsFlying
   *
   * @generated from field: required uint64 Flags = 3;
   */
  Flags: bigint;
};

/**
 * Describes the message PlayerInfo.
 * Use `create(PlayerInfoSchema)` to create a new message.
 */
export const PlayerInfoSchema: GenMessage<PlayerInfo> = /*@__PURE__*/
  messageDesc(file_Lakeshire, 1);

/**
 * @generated from message TargetInfo
 */
export type TargetInfo = Message<"TargetInfo"> & {
  /**
   * @generated from field: required Unit UnitInfo = 1;
   */
  UnitInfo?: Unit;
};

/**
 * Describes the message TargetInfo.
 * Use `create(TargetInfoSchema)` to create a new message.
 */
export const TargetInfoSchema: GenMessage<TargetInfo> = /*@__PURE__*/
  messageDesc(file_Lakeshire, 2);

/**
 * @generated from message Unit
 */
export type Unit = Message<"Unit"> & {
  /**
   * @generated from field: required string Name = 1;
   */
  Name: string;

  /**
   * @generated from field: required int64 Level = 2;
   */
  Level: bigint;

  /**
   * @generated from field: optional Class Class = 3;
   */
  Class: Class;

  /**
   * @generated from field: required int64 HealthCurrent = 4;
   */
  HealthCurrent: bigint;

  /**
   * @generated from field: required int64 HealthMax = 5;
   */
  HealthMax: bigint;

  /**
   * @generated from field: optional int64 PowerCurrent = 6;
   */
  PowerCurrent: bigint;

  /**
   * @generated from field: optional int64 PowerMax = 7;
   */
  PowerMax: bigint;
};

/**
 * Describes the message Unit.
 * Use `create(UnitSchema)` to create a new message.
 */
export const UnitSchema: GenMessage<Unit> = /*@__PURE__*/
  messageDesc(file_Lakeshire, 3);

/**
 * @generated from message Position
 */
export type Position = Message<"Position"> & {
  /**
   * @generated from field: required uint64 MapX = 1;
   */
  MapX: bigint;

  /**
   * @generated from field: required uint64 MapY = 2;
   */
  MapY: bigint;

  /**
   * @generated from field: required uint64 MapId = 3;
   */
  MapId: bigint;

  /**
   * @generated from field: required int64 WorldX = 4;
   */
  WorldX: bigint;

  /**
   * @generated from field: required int64 WorldY = 5;
   */
  WorldY: bigint;

  /**
   * @generated from field: required uint64 InstanceId = 6;
   */
  InstanceId: bigint;

  /**
   * @generated from field: required uint64 Facing = 7;
   */
  Facing: bigint;
};

/**
 * Describes the message Position.
 * Use `create(PositionSchema)` to create a new message.
 */
export const PositionSchema: GenMessage<Position> = /*@__PURE__*/
  messageDesc(file_Lakeshire, 4);

/**
 * @generated from enum BotState
 */
export enum BotState {
  /**
   * @generated from enum value: Stopped = 0;
   */
  Stopped = 0,

  /**
   * @generated from enum value: Running = 1;
   */
  Running = 1,

  /**
   * @generated from enum value: DumpPos = 2;
   */
  DumpPos = 2,
}

/**
 * Describes the enum BotState.
 */
export const BotStateSchema: GenEnum<BotState> = /*@__PURE__*/
  enumDesc(file_Lakeshire, 0);

/**
 * @generated from enum Class
 */
export enum Class {
  /**
   * @generated from enum value: None = 0;
   */
  None = 0,

  /**
   * @generated from enum value: Warrior = 1;
   */
  Warrior = 1,

  /**
   * @generated from enum value: Paladin = 2;
   */
  Paladin = 2,

  /**
   * @generated from enum value: Hunter = 3;
   */
  Hunter = 3,

  /**
   * @generated from enum value: Rogue = 4;
   */
  Rogue = 4,

  /**
   * @generated from enum value: Priest = 5;
   */
  Priest = 5,

  /**
   * @generated from enum value: DeathKnight = 6;
   */
  DeathKnight = 6,

  /**
   * @generated from enum value: Shaman = 7;
   */
  Shaman = 7,

  /**
   * @generated from enum value: Mage = 8;
   */
  Mage = 8,

  /**
   * @generated from enum value: Warlock = 9;
   */
  Warlock = 9,

  /**
   * @generated from enum value: Monk = 10;
   */
  Monk = 10,

  /**
   * @generated from enum value: Druid = 11;
   */
  Druid = 11,
}

/**
 * Describes the enum Class.
 */
export const ClassSchema: GenEnum<Class> = /*@__PURE__*/
  enumDesc(file_Lakeshire, 1);
