const ZONE_DATA = {
    'Kalimdor': [
        { name: 'Ashenvale', },
        { name: 'Azshara', },
        { name: 'Darkshore', },
        // { name: 'Darnassus', },
        { name: 'Desolace', },
        { name: 'Durotar',},
        { name: 'Dustwallow Marsh', imageName: 'Dustwallow' },
        { name: 'Felwood', },
        { name: 'Feralas', },
        // { name: 'Moonglade', },
        { name: 'Mulgore', },
        // { name: 'Orgrimmar', },
        { name: 'Silithus', },
        { name: 'Stonetalon Mountains', imageName: 'Stonetalon' },
        { name: 'Tanaris', },
        { name: 'Teldrassil', },
        { name: 'The Barrens', imageName: 'Barrens' },
        { name: 'Thousand Needles', imageName: 'ThousandNeedles' },
        // { name: 'Thunder Bluff', },
        { name: 'Un\'Goro Crater', imageName: 'Ungoro' },
        { name: 'Winterspring' },
    ],
    'Eastern Kingdoms': [
        { name: 'Alterac Mountains', imageName: 'Alterac' },
        { name: 'Arathi Highlands', imageName: 'Arathi' },
        { name: 'Badlands', },
        { name: 'Blasted Lands', imageName: 'BlastedLands' },
        { name: 'Burning Steppes', imageName: 'BurningSteppes' },
        // { name: 'Deadwind Pass' },
        { name: 'Dun Morogh', imageName: 'DunMorogh' },
        { name: 'Duskwood', },
        { name: 'Eastern Plaguelands', imageName: 'EasternPlaguelands' },
        { name: 'Elwynn Forest', imageName: 'Elwynn' },
        { name: 'Hillsbrad Foothills', imageName: 'Hillsbrad' },
        // { name: 'Ironforge', },
        { name: 'Loch Modan', imageName: 'LochModan' },
        { name: 'Redridge Mountains', imageName: 'Redridge'},
        { name: 'Searing Gorge', imageName: 'SearingGorge'},
        { name: 'Silverpine Forest', imageName: 'Silverpine' },
        // { name: 'Stormwind City', },
        { name: 'Stranglethorn Vale', imageName: 'Stranglethorn' },
        { name: 'Swamp of Sorrows', imageName: 'SwampofSorrows' },
        { name: 'The Hinterlands', imageName: 'Hinterlands' },
        { name: 'Tirisfal Glades', imageName: 'Tirisfal' },
        // { name: 'Undercity', },
        { name: 'Western Plaguelands', imageName: 'WesternPlaguelands' },
        { name: 'Westfall', },
        { name: 'Wetlands' },
    ]
}

export default ZONE_DATA;
